{
  "extends": "eslint:recommended",
  "rules": {
    "quotes": "off", 
    "semi": "off",
    "indent": ["error", 4],
    "space-before-blocks": ["error", "never"],
    "space-before-function-paren": ["error", "never"],
    "space-in-parens": ["error", "never"],
    "spaced-comment": ["error", "always"],
    "brace-style": "stroustrup",
  }
}
