{
  "extends": "eslint:recommended",
  "rules": {
    "semi": "always",
    "indent": ["error", 4],
    "space-before-function-paren": ["error", "never"],
    "space-in-parens": ["error", "never"],
    "brace-style": "stroustrup",
  }
}
