{
  "extends": "eslint:recommended",
  "rules": {
    "semi": ["error", "always"],
    "indent": ["error", "tab"],
    "space-before-function-paren": ["error", "never"],
    "space-in-parens": ["error", "never"],
  }
}
