---

#############################
#############################
## JavaScript Linter rules ##
#############################
#############################

############
# Env Vars #
############
env:
  browser: true
  es6: true
  jest: true

###############
# Global Vars #
###############
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly

###############
# Parser vars #
###############
parser: babel-eslint

###########
# Extends #
###########
extends: standard
#########
# Rules #
#########
rules: {
  "no-tabs": 0,
  "semi": ["error", "always"],
  "indent": ["error", "tab"],
  "space-before-function-paren": ["error", "never"],
  "space-in-parens": ["error", "never"],
}
