name: Create JSDoc

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      # Checks out code base
      - name: Checkout code
        uses: actions/checkout@v2
      
      # Builds JSDoc in md form
      - name: Build docs
        run: |
            npm install jsdoc-to-markdown
            npm run docs
      
      # Uploads JSDoc to Wiki page
      - name: Upload JSDoc to Wiki
        uses: SwiftDocOrg/github-wiki-publish-action@v1
        with:
          path: "./docs"
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{secrets.GH_PERSONAL_ACCESS_TOKEN}}
     
