name: Create JSDoc

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build docs
        uses: andstor/jsdoc-action@v1.2.0
        with:
          source_dir: ./source
          output_dir: ./docs  
          recurse: true
      
      - name: Add to Repo
        run: |
          git config --local user.email "esong165@gmail.com"
          git config --local user.name "esong165"
          git fetch
          git rm --cached
          git checkout documentation
          git add .
          git commit -m "Added JSDoc"
          git push
        
      - name: Upload to Pages
        uses: ./
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          remote_url: https://github.com/esong165/cse110-w21-group25.git
          target_branch: main
     
