name: Create JSDoc

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build docs
        uses: andstor/jsdoc-action@v1.2.0
        with:
          source_dir: ./source
          output_dir: ./docs  
          recurse: true
          
      - name: Build docs
        run: |
            npm install --save-dev jsdoc-to-markdown
            jsdoc2md source/*.js > JSDoc.md  
      
      - name: Upload JSDoc to Wiki
        uses: SwiftDocOrg/github-wiki-publish-action@v1
        with:
          path: "./docs"
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{secrets.GH_PERSONAL_ACCESS_TOKEN}}
     
