# Basic workflow to deploy /source to GH Pages

name: Deploy to GH Pages

# Controls when the action will run. 
on:
  # Triggers the workflow on push to the main branch
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Deploys source to GitHub Pages 
      - name: Deploy source to GitHub Pages
        run: |
          find . -maxdepth 1 ! -name 'source' ! -name '.git' -delete
          find source -maxdepth 1 -exec mv {} . \;
          find . -name '*.test.js' -type f -delete
          git config --global user.email 'DuckDuckWhaleUCSD@github.com'
          git config --global user.name 'DuckDuckWhaleUCSD'
          git add -A
          git commit -m 'Deploy: remove tests and deploy to GitHub'
          git push -f origin main:gh-pages
